name: Connection Checker CI workflow

on:
  push:
    branches:
      - main    # triggering the workflow on push to main

jobs:
  build:
    runs-on: ubuntu-latest # running on ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # getting source code from repo

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # dockerhub username
          password: ${{ secrets.DOCKER_PASSWORD }}  # dockerhub password

      - name: Build Docker Image
        run: docker build -t mazivazvose/connection-checker . # buiding image with Dockerfile

      - name: List images
        run: docker images    # listing the build images 

      - name: Push Docker Image
        run: docker push mazivazvose/connection-checker # pushing the image to Docker Hub
